---
- hosts: all
  become: yes
  tasks:
    - name: Add Zabbix repo
      yum:
        name: https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
        state: latest
    - name: install zabbix agent
      yum:
        name: zabbix-agent
        state: latest
    - name: start the zabbix-agent
      service:
        name: zabbix-agent
        state: started
        enabled: yes
