---
- hosts: all
  become: yes
  tasks:
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      unarchive:
        src: https://www.zabbix.com/downloads/5.0.2/zabbix_agent-5.0.2-linux-3.0-amd64-static.tar.gz
        dest: /usr/local/bin
        remote_src: yes
